version: '3.6'

services:
  backend:
    networks:
      - vps
    image: node:12.14.0
    container_name: backend
    ports:
      - "3001:3001"
    restart: unless-stopped
    volumes:
      - $PWD:/app
    command: sh -c "cd /app && npm run start"

networks:
  vps:
    name: vps
